#!/bin/bash

scriptName="tmp_conifg"

function clean() {
  echo "Download failed :<"
  if [ -f $scriptName ]; then
    rm -f $scriptName
  fi
  exit 1
}

trap 'clean' 1 2 3 15


curl "https://raw.githubusercontent.com/goods-inc/config-files/master/init" > $scriptName

bash $scriptName
