#!/bin/bash

trap 'echo "Download failed :<"; exit 1' 1 2 3 15

files=(.eslintrc .editorconfig)

URL="https://raw.githubusercontent.com/goods-inc/config-files/master"
logo='
    ___   ________           ________   ________   ________    ________  ___   ________
   |\  \ |\   ____\         |\   ____\ |\   __  \ |\   ___  \ |\  _____\|\  \ |\   ____\
   \ \  \\ \  \___|_        \ \  \___| \ \  \|\  \\ \  \\ \  \\ \  \__/ \ \  \\ \  \___|
 __ \ \  \\ \_____  \        \ \  \     \ \  \\\  \\ \  \\ \  \\ \   __\ \ \  \\ \  \  ___
|\  \\_\  \\|____|\  \        \ \  \____ \ \  \\\  \\ \  \\ \  \\ \  \_|  \ \  \\ \  \|\  \
\ \________\ ____\_\  \        \ \_______\\ \_______\\ \__\\ \__\\ \__\    \ \__\\ \_______\
 \|________||\_________\        \|_______| \|_______| \|__| \|__| \|__|     \|__| \|_______|
            \|_________|

'

if [ ! -f "package.json" ]; then
  print  "Run npm init. Ok?[Y/n] "
  read ans
  case $ans in
    "n" | "N") exit 0 ;;
    *) npm init
  esac
fi

npm install --save-dev eslint-config-airbnb eslint-plugin-import eslint-plugin-react eslint-plugin-jsx-a11y eslint

echo "Start downloading ${files[@]} ..."
for file in ${files[@]}
do
  curl -sO "$URL/$file"
  echo "Download $file"
done

echo "Download fininshed!!"
echo "$logo"
